cp ../map/map.pdf figures/
cp ../figures/KAP103/timeseries.png figures/KAP103
cp ../figures/KAP103/SN_compare-E_x.pdf figures/KAP103
cp ../figures/KAP103/SN_compare-E_y.pdf figures/KAP103
cp ../figures/KAP103/transferfnZ_compare-Z_xx_Magnitude_Phase.pdf figures/KAP103
cp ../figures/KAP103/transferfnZ_compare-Z_xy_Magnitude_Phase.pdf figures/KAP103
cp ../figures/KAP103/transferfnZ_compare-Z_yx_Magnitude_Phase.pdf figures/KAP103
cp ../figures/KAP103/transferfnZ_compare-Z_yy_Magnitude_Phase.pdf figures/KAP103
cp ../figures/KAP103_Middelpos/SN_compare-E_x.pdf figures/KAP103_Middelpos
cp ../figures/KAP103_Middelpos/SN_compare-E_y.pdf figures/KAP103_Middelpos
cp ../figures/KAP103_Middelpos/transferfnZ_compare-Z_xx_Magnitude_Phase.pdf figures/KAP103_Middelpos
cp ../figures/KAP103_Middelpos/transferfnZ_compare-Z_xy_Magnitude_Phase.pdf figures/KAP103_Middelpos
cp ../figures/KAP103_Middelpos/transferfnZ_compare-Z_yx_Magnitude_Phase.pdf figures/KAP103_Middelpos
cp ../figures/KAP103_Middelpos/transferfnZ_compare-Z_yy_Magnitude_Phase.pdf figures/KAP103_Middelpos
